### ISSUE TITLE
how to run in a single system (ssh/sample_ssh.py)

### ISSUE THREAD

**Issue by debasish2110** [debasish2110/Socket_python#1]
I am using Linux but don't know how to set the host and port. The code written in sample_ssh.py file is client, as it uses socket.connect() method, can we write a server code for the same?

**Comment by 99004336-SriHarshith** [comment]
Try to create a server in your machine by following steps mentioned in the below link:- https://www.google.com/amp/s/www.cyberciti.biz/faq/ubuntu-linux-install-openssh-server/

Then update the host to localhost, port 22, user and password of your local machine in the code.

**Comment by debasish2110** [comment]
Thank you hashish. It worked
